const http = require('http');
const crypto = require('crypto');

const APP_SECRET = 'client secret'; //secret of the App Partner
const REQUEST_BODY = 'req.data'; //the body content of the webhook request
const SIGNATURE = 'x-linkedstore-hmac-sha256'; //the header of the webhook request

const server = http
.createServer((req, res) => {
    const header = req.headers['x-linkedstore-hmac-sha256'];
    const hmac = crypto.createHmac('sha256',APP_SECRET  );
    req.on('data', (chunk) => {
      hmac.update(chunk);
    })
      .on('end', () => {
        const hash = hmac.digest('hex');
        console.log('signature from header generated by webhook:', header);
        console.log('validated signature: ', hash);
        res.writeHead(204);
        res.end();
      });
  })
  .listen(1313, () => {
    const request = http.request({
      host: 'localhost',
      port: 1313,
      method: 'POST',
    }, () => {
      server.close();
    });

    request.setHeader('x-linkedstore-hmac-sha256', SIGNATURE);

    request.write(REQUEST_BODY);
    request.end();
  });